version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: serpadmin
      MINIO_NOTIFY_AMQP_ENABLE_primary: on
      MINIO_NOTIFY_AMQP_URL_primary: 'amqp://guest:guest@rabbitmq:5672'
      MINIO_NOTIFY_AMQP_EXCHANGE_primary: minio
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_primary: fanout
      MINIO_NOTIFY_AMQP_DURABLE_primary: on
#      MINIO_NOTIFY_AMQP_ROUTING_KEY_SERP: xx 
    command: server --console-address ":9001" /data
    networks:
        - rabbitmq_go_net

  minio2:
    image: minio/minio
    container_name: minio2
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: serpadmin
      MINIO_NOTIFY_AMQP_ENABLE_primary: on
      MINIO_NOTIFY_AMQP_URL_primary: 'amqp://guest:guest@rabbitmq:5672'
      MINIO_NOTIFY_AMQP_EXCHANGE_primary: minio2
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_primary: fanout
      MINIO_NOTIFY_AMQP_DURABLE_primary: on
#      MINIO_NOTIFY_AMQP_ROUTING_KEY_SERP: xx 
    command: server --console-address ":9011" /data
    networks:
        - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitdata:/var/lib/rabbitmq/
        - rabbitlog:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net


networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  minio_storage: {}
  rabbitdata: {}
  rabbitlog: {}